---
abstract: 'Encode fractions as HTML entities'
author:
  - "Leon Brocard, C<< <acme@astray.com> >>. Mark Fowler C<< <mark@twoshortplanks> >>\nadded some code, and probably some bugs."
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Fraction
provides:
  HTML::Fraction:
    file: lib/HTML/Fraction.pm
    version: 0.50
requires:
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.40
