---
name: HTML-Fraction
version: 0.29
author:
  - 'Leon Brocard, C<< <acme@astray.com> >>'
abstract: Encode fractions as HTML entities
license: perl
requires:
  Test::More: 0
provides:
  HTML::Fraction:
    file: lib/HTML/Fraction.pm
    version: 0.29
generated_by: Module::Build version 0.261
